-- Run this once in the Supabase SQL Editor before the first pipeline run.
-- Supabase Dashboard → SQL Editor → New query → paste → Run.
--
-- order_id is a UUID generated by the ETL pipeline and acts as the primary
-- key, making every upsert idempotent (safe to re-run without duplicates).
--
-- Power BI connection:
--   Home → Get Data → PostgreSQL → use your Supabase "Session pooler"
--   host (Project Settings → Database → Connection string).
--   Database: postgres   Schema: public   Table: sales

CREATE TABLE IF NOT EXISTS public.sales (
    order_id                 TEXT          PRIMARY KEY,

    -- Dates
    date_of_sale             DATE,
    date_of_listing          DATE,
    time_of_sale             TEXT,

    -- Item details
    brand                    TEXT,
    description              TEXT,
    size                     TEXT,
    category                 TEXT,
    bundle                   TEXT,

    -- Financials (USD)
    item_price               NUMERIC(10,2),
    buyer_shipping_cost      NUMERIC(10,2),
    total                    NUMERIC(10,2),
    depop_fee                NUMERIC(10,2),
    depop_payments_fee       NUMERIC(10,2),
    boosting_fee             NUMERIC(10,2),
    us_sales_tax             NUMERIC(10,2),
    refunded_to_buyer_amount NUMERIC(10,2),
    fees_refunded_to_seller  NUMERIC(10,2),

    -- Shipping / location
    payment_type             TEXT,
    city                     TEXT,
    state                    TEXT,
    post_code                TEXT,
    country                  TEXT,

    -- Derived
    time_to_sell_days        INTEGER
);

-- Index used by most date-based Power BI filters and charts
CREATE INDEX IF NOT EXISTS idx_sales_date_of_sale ON public.sales (date_of_sale);
